version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
