name: Deploy to DigitalOcean

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd id
            git pull
            docker-compose -f docker-compose.yml down --remove-orphans
            docker rm -f $(docker ps -a -q)
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml up -d
